<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">

            <h1>Обновление данных пользователя</h1>

            <form action="/users/<?= $user['id'] ?>" method="post">
                <input type="hidden" name="_METHOD" value="PATCH">

                <div class="form-group">
                    <label for="name">New name</label>
                    <input type="text" class="form-control" name="user[name]" placeholder="<?= htmlspecialchars($user['name'] ?? ''); ?>">
                    <?php if (isset($errors['name'])) : ?>
                        <font color="red"><?= $errors['name'] ?></font>
                    <?php endif ?>
                </div>

                <div class="form-group">
                    <label for="email"> New email</label>
                    <input type="text" class="form-control" name="user[email]" placeholder="<?= htmlspecialchars($user['email'] ?? ''); ?>">
                    <?php if (isset($errors['email'])) : ?>
                        <font color="red"><?= $errors['email'] ?></font>
                    <?php endif ?>
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary mb-3" value="Update">
                </div>

            </form>

            <form action="/users">
                <input type="submit" class="btn btn-outline-success" value="All users">
            </form>

        </div>
    </div>
</div>