<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1>Регистрация</h1>
            <form action="/users" method="post">
                <div class="form-group">
                    <label for="name">Имя</label>
                    <input type="text" class="form-control" name="user[name]" value="<?= $user['name'] ?>">
                    <?php if (isset($errors['name'])) : ?>
                        <font color="red"><?= $errors['name'] ?></font>
                    <?php endif ?>
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input type="text" class="form-control" name="user[email]" value="<?= $user['email'] ?>">
                    <?php if (isset($errors['email'])) : ?>
                        <font color="red"><?= $errors['email'] ?></font>
                    <?php endif ?>
                </div>
                <div class="form-group">
                    <label>User ID </label>
                    <input type="text" class="form-control" name="user[id]" value="<?= $user['id'] ?>">
                    <input type="submit" class="btn btn-primary mb-3" value="Create">
                </div>
            </form>
        </div>
    </div>
</div>